#ifdef _MSC_VER
#pragma execution_character_set("utf-8")
#endif
#pragma once
#include <string>
#include <QIntegerForSize>
#include "self_define.h"

//typedef struct Item
//{
//    std::string ItemName;
//    int ItemLength;
//}ATPItem;


class Analyze_ATPMessage
{
public:
    Analyze_ATPMessage();
    struct
    {
        std::string ItemName;
        unsigned int ItemLength;
        qint64 value;
    }Detail_LS[429]=
    {
        {"MAINT_NIVEAU_ANNONCE",	8,-1},
        {"MAINT_NIVEAU",	8,-1},
        {"MAINT_MODE",	8,-1},
        {"MAINT_POS_TRAIN",	32,-1},
        {"MAINT_VIT_TRAIN",	16,-1},
        {"MAINT_POS_GEO",	32,-1},
        {"MAINT_DIS_DEB_FREINAGE",	32,-1},
        {"MAINT_DIS_BUT",	32,-1},
        {"MAINT_VIT_BUT",	16,-1},
        {"MAINT_DIS_OBJECTIF",	32,-1},
        {"MAINT_VIT_OBJECTIF",	16,-1},
        {"MAINT_VIT_PERMISE",	16,-1},
        {"MAINT_VIT_LIBERATION",	16,-1},
        {"MAINT_VIT_PRE_INTERV",	16,-1},
        {"MAINT_ALLOC_DISPO",	8,-1},
        {"MAINT_OBJECTIF_EXISTE",	1,-1},
        {"MAINT_NOUVEL_OBJECTIF",	1,-1},
        {"MAINT_ZONE_MOD_PROF",	1,-1},
        {"MAINT_PRES_ALLOC",	1,-1},
        {"MAINT_REVERSE_EN_COURS",	1,-1},
        {"MAINT_ROLLAWAY_EN_COURS",	1,-1},
        {"MAINT_SUP_FREINAGE",	1,-1},
        {"MAINT_FIN_MISSION",	1,-1},
        {"MAINT_D_TRAIN_ACCEPTEES",	1,-1},
        {"MAINT_ERR_INFO_BORD",	1,-1},
        {"MAINT_ETAT_DIAL_MMI",	5,-1},
        {"MAINT_L_DOUBTOVER",	16,-1},
        {"MAINT_L_DOUBTUNDER",	16,-1},
        {"MAINT_STANDSTILL_PROTECT_SR",	1,-1},
        {"MAINT_CSD_CYCLE",	32,-1},
        {"MAINT_NOTIFY_SF",	8,-1},
        {"MAINT_POS_ODO",	32,-1},
        {"MAINT_ERR_POSITIVE",	32,-1},
        {"MAINT_ERR_NEGATIVE",	32,-1},
        {"MAINT_VIT_ODO",	16,-1},
        {"MAINT_VIT_SUP",	16,-1},
        {"MAINT_VIT_INF",	16,-1},
        {"MAINT_POS_BALISE",	32,-1},
        {"MAINT_PRES_BALISE",	1,-1},
        {"MAINT_SENS_ODO",	2,-1},
        {"MAINT_ARRET_TRAIN",	1,-1},
        {"MAINT_ETAT_ODO",	2,-1},
        {"MAINT_ERR_INFO_ODO",	1,-1},
        {"RESERVE__ODO_01",	1,-1},
        {"MAINT_LONGUEUR_ZONE",	32,-1},
        {"MAINT_ID_BALISE_IN",	16,-1},
        {"MAINT_ID_BALISE_OUT",	16,-1},
        {"MAINT_ETAT_CTL_CALIB",	2,-1},
        {"MAINT_ERR_INFO_AUTOCAL",	1,-1},
        {"RES_CALIB",	5,-1},
        {"MAINT_SEL_DONNEES",	8,-1},
        {"MAINT_CAB_CONDUCT",	2,-1},
        {"MAINT_CAB_TETE",	2,-1},
        {"MAINT_UNITE_SIMPLE",	1,-1},
        {"MAINT_FREIN_PASSAGER",	1,-1},
        {"MAINT_SLEEPING",	1,-1},
        {"MAINT_ISOLATION",	1,-1},
        {"MAINT_PRESSION_FU",	1,-1},
        {"MAINT_BOUTON_ALERTE",	1,-1},
        {"MAINT_QAR",	1,-1},
        {"MAINT_QAV",	1,-1},
        {"MAINT_CMD_FU",	1,-1},
        {"MAINT_CMD_FS",	1,-1},
        {"MAINT_CMD_INHIB_PASSAGER",	1,-1},
        {"MAINT_CMD_COUPER_TRACTION",	1,-1},
        {"MAINT_CMD_OUV_DISJONCTEUR",	1,-1},
        {"MAINT_CMD_BAISSER_PANTOGRAPHE",	1,-1},
        {"MAINT_CMD_COND_AIR",	1,-1},
        {"MAINT_CMD_OUV_PORTE_G",	1,-1},
        {"MAINT_CMD_OUV_PORTE_D",	1,-1},
        {"MAINT_CMD_NON_DEF_EUROCAB",	1,-1},
        {"MAINT_CMD_TRAIN_A_L_ARRET",	1,-1},
        {"MAINT_ERR_INFO_TIU",	1,-1},
        {"MAINT_CMD_FU_2",	1,-1},
        {"MAINT_REL_APP_FU_1",	1,-1},
        {"MAINT_REL_APP_FU_2",	1,-1},
        {"MAINT_REL_APP_FS",	1,-1},
        {"MAINT_NEUTRAL_ZONE_IND",	1,-1},
        {"MAINT_NEUTRAL_ZONE_CMD",	1,-1},
        {"MAINT_NEUTRAL_ZONE_ISOLATION",	1,-1},
        {"MAINT_NEUTRAL_ZONE_INHIBIT",	1,-1},
        {"MAINT_NO_TELEG_E",	8,-1},
        {"MAINT_PAQ_TELEG_E_1",	8,-1},
        {"MAINT_PAQ_TELEG_E_2",	8,-1},
        {"MAINT_PAQ_TELEG_E_3",	8,-1},
        {"MAINT_PAQ_TELEG_E_4",	8,-1},
        {"MAINT_NO_PAQ_ERRONE_RBC_E",	8,-1},
        {"MAINT_NO_TELEG_R",	8,-1},
        {"MAINT_PAQ_TELEG_R_1",	8,-1},
        {"MAINT_PAQ_TELEG_R_2",	8,-1},
        {"MAINT_PAQ_TELEG_R_3",	8,-1},
        {"MAINT_PAQ_TELEG_R_4",	8,-1},
        {"MAINT_PAQ_TELEG_R_5",	8,-1},
        {"MAINT_PAQ_TELEG_R_6",	8,-1},
        {"MAINT_PAQ_TELEG_R_7",	8,-1},
        {"MAINT_PAQ_TELEG_R_8",	8,-1},
        {"MAINT_PAQ_TELEG_R_9",	8,-1},
        {"MAINT_PAQ_TELEG_R_10",	8,-1},
        {"MAINT_NO_PAQ_ERRONE_RBC_R",	8,-1},
        {"MAINT_PAQ_TELEG_T_1",	8,-1},
        {"MAINT_PAQ_TELEG_T_2",	8,-1},
        {"MAINT_PAQ_TELEG_T_3",	8,-1},
        {"MAINT_PAQ_TELEG_T_4",	8,-1},
        {"MAINT_PAQ_TELEG_T_5",	8,-1},
        {"MAINT_PAQ_TELEG_T_6",	8,-1},
        {"MAINT_PAQ_TELEG_T_7",	8,-1},
        {"MAINT_PAQ_TELEG_T_8",	8,-1},
        {"MAINT_PAQ_TELEG_T_9",	8,-1},
        {"MAINT_PAQ_TELEG_T_10",	8,-1},
        {"MAINT_PAQ_BALISE_1",	8,-1},
        {"MAINT_PAQ_BALISE_2",	8,-1},
        {"MAINT_PAQ_BALISE_3",	8,-1},
        {"MAINT_PAQ_BALISE_4",	8,-1},
        {"MAINT_PAQ_BALISE_5",	8,-1},
        {"MAINT_PAQ_BALISE_6",	8,-1},
        {"MAINT_PAQ_BALISE_7",	8,-1},
        {"MAINT_PAQ_BALISE_8",	8,-1},
        {"MAINT_PAQ_BALISE_9",	8,-1},
        {"MAINT_PAQ_BALISE_10",	8,-1},
        {"MAINT_NO_PAQ_ERRONE_BTM",	8,-1},
        {"MAINT_PAQ_BALISE_T_1",	8,-1},
        {"MAINT_PAQ_BALISE_T_2",	8,-1},
        {"MAINT_PAQ_BALISE_T_3",	8,-1},
        {"MAINT_PAQ_BALISE_T_4",	8,-1},
        {"MAINT_PAQ_BALISE_T_5",	8,-1},
        {"MAINT_PAQ_BALISE_T_6",	8,-1},
        {"MAINT_PAQ_BALISE_T_7",	8,-1},
        {"MAINT_PAQ_BALISE_T_8",	8,-1},
        {"MAINT_PAQ_BALISE_T_9",	8,-1},
        {"MAINT_PAQ_BALISE_T_10",	8,-1},
        {"MAINT_ERR_VAR_TELEG_E",	1,-1},
        {"MAINT_ERR_VAR_TELEG_R",	1,-1},
        {"RESERVE_SOL_01",	2,-1},
        {"RESERVE_SOL_02",	2,-1},
        {"RESERVE_SOL_03",	2,-1},
        {"MAINT_EFFACER_CHAINAGE",	1,-1},
        {"MAINT_RACCOURCIR_CHAINAGE",	1,-1},
        {"MAINT_EFFACER_ALLOCATION",	1,-1},
        {"MAINT_RACCOURCIR_ALLOCATION",	1,-1},
        {"MAINT_EFFACER_PROFILS",	1,-1},
        {"MAINT_RACCOURCIR_PROFILS",	1,-1},
        {"MAINT_EFFACER_TRANSITION_NIVEAU",	1,-1},
        {"MAINT_EFFACER_LISTE_BALISES_SH",	1,-1},
        {"MAINT_REINIT_MA_REQUEST",	1,-1},
        {"MAINT_REINIT_POSITION_REPORT",	1,-1},
        {"MAINT_EFFACER_LISTE_BALISES_SR",	1,-1},
        {"MAINT_EFFACER_DISTANCE_SR",	1,-1},
        {"MAINT_EFFACER_RESTRICTION_VITESSE",	1,-1},
        {"MAINT_EFFACER_DEFAUT_GRADIENT_TSR",	1,-1},
        {"MAINT_EFFACER_VITESSE_SIGNALISATION",	1,-1},
        {"MAINT_EFFACER_ROUTE_SUITABILITY",	1,-1},
        {"MAINT_RACCOURCIR_ROUTE_SUITABILITY",	1,-1},
        {"MAINT_REINIT_COEFFICIENT_ADHESION",	1,-1},
        {"MAINT_EFFACER_MESSAGES_TXT",	1,-1},
        {"MAINT_EFFACER_POSITION_GEOGRAPHIQUE",	1,-1},
        {"MAINT_EFFACER_MODE_PROFILE",	1,-1},
        {"MAINT_EFFACER_TRANSITION_RBC",	1,-1},
        {"MAINT_EFFACER_TRACKCONDITIONS",	1,-1},
        {"MAINT_RACCOURCIR_TRACKCONDITION",	1,-1},
        {"MAINT_EFFACER_CHANGEMENT_TRACTION",	1,-1},
        {"MAINT_RACCOURCIR_CHANGEMENT_TRACTION",	1,-1},
        {"MAINT_EFFACER_ARRET_BTM",	1,-1},
        {"MAINT_RACCOURCIR_ARRET_BTM",	1,-1},
        {"MAINT_EFFACER_ARRET_URGENT",	1,-1},
        {"MAINT_EFFACER_ID_DRIVER",	1,-1},
        {"MAINT_EFFACER_INFOS_RBC",	1,-1},
        {"MAINT_EFFACER_ID_MISSION",	1,-1},
        {"MAINT_EFFACER_REVERSING_AREA",	1,-1},
        {"MAINT_RACCOURCIR_REVERSING_AREA",	1,-1},
        {"MAINT_EFFACER_REVERSING_SUPERVISION",	1,-1},
        {"RESERVE_EFFACER_01",	5,-1},
        {"MAINT_PAQ_MMI_E_1",	8,-1},
        {"MAINT_PAQ_MMI_E_2",	8,-1},
        {"MAINT_PAQ_MMI_E_3",	8,-1},
        {"MAINT_PAQ_MMI_E_4",	8,-1},
        {"MAINT_PAQ_MMI_E_5",	8,-1},
        {"MAINT_PAQ_MMI_E_6",	8,-1},
        {"MAINT_NO_PAQ_ERRONE_MMI_E",	8,-1},
        {"MAINT_PAQ_MMI_R_1",	8,-1},
        {"MAINT_PAQ_MMI_R_2",	8,-1},
        {"MAINT_PAQ_MMI_R_3",	8,-1},
        {"MAINT_PAQ_MMI_R_4",	8,-1},
        {"MAINT_PAQ_MMI_R_5",	8,-1},
        {"MAINT_PAQ_MMI_R_6",	8,-1},
        {"MAINT_NO_PAQ_ERRONE_MMI_R",	8,-1},
        {"MAINT_PQT_53_LENGTH",	8,-1},
        {"MAINT_PQT_53_D_S_TYPE",	8,-1},
        {"MAINT_TEXT_LENGTH",	8,-1},
        {"MAINT_TEXT_BUFFER_01",	8,-1},
        {"MAINT_TEXT_BUFFER_02",	8,-1},
        {"MAINT_TEXT_BUFFER_03",	8,-1},
        {"MAINT_TEXT_BUFFER_04",	8,-1},
        {"MAINT_TEXT_BUFFER_05",	8,-1},
        {"MAINT_TEXT_BUFFER_06",	8,-1},
        {"MAINT_TEXT_BUFFER_07",	8,-1},
        {"MAINT_TEXT_BUFFER_08",	8,-1},
        {"MAINT_TEXT_BUFFER_09",	8,-1},
        {"MAINT_TEXT_BUFFER_10",	8,-1},
        {"MAINT_TEXT_BUFFER_11",	8,-1},
        {"MAINT_TEXT_BUFFER_12",	8,-1},
        {"MAINT_TEXT_BUFFER_13",	8,-1},
        {"MAINT_TEXT_BUFFER_14",	8,-1},
        {"MAINT_TEXT_BUFFER_15",	8,-1},
        {"MAINT_TEXT_BUFFER_16",	8,-1},
        {"MAINT_TEXT_BUFFER_17",	8,-1},
        {"MAINT_TEXT_BUFFER_18",	8,-1},
        {"MAINT_TEXT_BUFFER_19",	8,-1},
        {"MAINT_TEXT_BUFFER_20",	8,-1},
        {"MAINT_TEXT_BUFFER_21",	8,-1},
        {"MAINT_TEXT_BUFFER_22",	8,-1},
        {"MAINT_TEXT_BUFFER_23",	8,-1},
        {"MAINT_TEXT_BUFFER_24",	8,-1},
        {"MAINT_TEXT_BUFFER_25",	8,-1},
        {"MAINT_TEXT_BUFFER_26",	8,-1},
        {"MAINT_TEXT_BUFFER_27",	8,-1},
        {"MAINT_TEXT_BUFFER_28",	8,-1},
        {"MAINT_TEXT_BUFFER_29",	8,-1},
        {"MAINT_TEXT_BUFFER_30",	8,-1},
        {"MAINT_TYPE_DMI",	2,-1},
        {"MAINT_DMI_RESERVE",	6,-1},
        {"MAINT_LOC_ID_BALISE_ATTENDUE",	16,-1},
        {"MAINT_LOC_SENS_BALISE_ATTENDUE",	8,-1},
        {"MAINT_LOC_POS_BALISE_ATTENDUE",	32,-1},
        {"MAINT_LOC_POS_BALISE_INF",	32,-1},
        {"MAINT_LOC_POS_BALISE_SUP",	32,-1},
        {"MAINT_LOC_POS_BALISE_LIMIT",	32,-1},
        {"MAINT_LOC_ACTION_PREVUE",	8,-1},
        {"MAINT_LOC_ACTION_EN_COURS",	1,-1},
        {"MAINT_LOC_BALISE_RENCONTREE_OK",	1,-1},
        {"MAINT_LOC_SENS_ODO",	2,-1},
        {"MAINT_LOC_SENS_TIU",	2,-1},
        {"MAINT_LOC_SENS_MA",	2,-1},
        {"MAINT_LOC_ACTION_REVERSE",	8,-1},
        {"MAINT_LOC_POSITION_REVERSE",	32,-1},
        {"MAINT_LOC_ACTION_ROLL_AWAY",	8,-1},
        {"MAINT_LOC_POSITION_ROLL_AWAY",	32,-1},
        {"MAINT_RBC_ETAT_COURANT",	4,-1},
        {"MAINT_RBC_ETAT_ACCEPTING",	4,-1},
        {"MAINT_RBC_ETAT_HANDOVER",	4,-1},
        {"MAINT_RBC_NB_GSM_DISPONIBLE",	2,-1},
        {"RESERVE_RBC_01",	2,-1},
        {"MAINT_DERNIERE_RECUE_POSITION",	32,-1},
        {"MAINT_DERNIERE_RECUE_ID_BAL",	16,-1},
        {"MAINT_DERNIERE_RECUE_SENS",	4,-1},
        {"MAINT_DERNIERE_RECUE_TYPE",	4,-1},
        {"MAINT_CEB_ETAT_CONTROLE",	4,-1},
        {"MAINT_CEB_ETAT_INIT_DT",	4,-1},
        {"MAINT_CEB_ETAT_MTOR",	4,-1},
        {"MAINT_CEB_ETAT_CIR",	4,-1},
        {"MAINT_CEB_ETAT_BTM",	4,-1},
        {"MAINT_CEB_ETAT_MMI",	4,-1},
        {"MAINT_KV_VIT_CTRL_FI",	16,-1},
        {"MAINT_KV_VIT_CTRL_FU",	16,-1},
        {"MAINT_KV_VIT_CTRL_FS_FU",	16,-1},
        {"MAINT_KV_CHGT_ARRET_URGENT",	1,-1},
        {"MAINT_KV_FI_EST_FS",	1,-1},
        {"MAINT_KV_CTRL_VIT_LIB",	1,-1},
        {"MAINT_KV_CALCUL_COURBE",	1,-1},
        {"RESERVE_KV_02",	2,-1},
        {"RESERVE_KV_03",	2,-1},
        {"MAINT_O_BRAKETARGET",	32,-1},
        {"MAINT_V_TARGET",	16,-1},
        {"MAINT_TIMER_CTRL",	32,-1},
        {"MAINT_DEFAUT_FU_SANCTIONNABLE",	1,-1},
        {"MAINT_TIMER_ECHU",	1,-1},
        {"RESERVE_CTRL_FU",	6,-1},
        {"MAINT_APP_VERSION_A",	8,-1},
        {"MAINT_APP_VERSION_B",	8,-1},
        {"MAINT_APP_VERSION_C",	8,-1},
        {"MAINT_APP_VERSION_D",	8,-1},
        {"MAINT_DMI_VERSION_A",	8,-1},
        {"MAINT_DMI_VERSION_B",	8,-1},
        {"MAINT_DMI_VERSION_C",	8,-1},
        {"MAINT_DMI_VERSION_D",	8,-1},
        {"MAINT_BTM_VERSION_A",	8,-1},
        {"MAINT_BTM_VERSION_B",	8,-1},
        {"MAINT_BTM_VERSION_C",	8,-1},
        {"MAINT_BTM_VERSION_D",	8,-1},
        {"MAINT_CFSK_VERSION_A",	8,-1},
        {"MAINT_CFSK_VERSION_B",	8,-1},
        {"MAINT_CFSK_VERSION_C",	8,-1},
        {"MAINT_CFSK_VERSION_D",	8,-1},
        {"MAINT_ODO1_VERSION_A",	8,-1},
        {"MAINT_ODO1_VERSION_B",	8,-1},
        {"MAINT_ODO1_VERSION_C",	8,-1},
        {"MAINT_ODO1_VERSION_D",	8,-1},
        {"MAINT_ODO2_VERSION_A",	8,-1},
        {"MAINT_ODO2_VERSION_B",	8,-1},
        {"MAINT_ODO2_VERSION_C",	8,-1},
        {"MAINT_ODO2_VERSION_D",	8,-1},
        {"MAINT_ODO3_VERSION_A",	8,-1},
        {"MAINT_ODO3_VERSION_B",	8,-1},
        {"MAINT_ODO3_VERSION_C",	8,-1},
        {"MAINT_ODO3_VERSION_D",	8,-1},
        {"MAINT_CURRENT_CHAIN",	8,-1},
        {"MAINT_NB_TRACKCOND",	8,-1},
        {"MAINT_Type_Cond_1",	8,-1},
        {"MAINT_Pos_Deb_1",	32,-1},
        {"MAINT_Pos_Fin_1",	32,-1},
        {"MAINT_Type_Cond_2",	8,-1},
        {"MAINT_Pos_Deb_2",	32,-1},
        {"MAINT_Pos_Fin_2",	32,-1},
        {"MAINT_Type_Cond_3",	8,-1},
        {"MAINT_Pos_Deb_3",	32,-1},
        {"MAINT_Pos_Fin_3",	32,-1},
        {"MAINT_Type_Cond_4",	8,-1},
        {"MAINT_Pos_Deb_4",	32,-1},
        {"MAINT_Pos_Fin_4",	32,-1},
        {"MAINT_Type_Cond_5",	8,-1},
        {"MAINT_Pos_Deb_5",	32,-1},
        {"MAINT_Pos_Fin_5",	32,-1},
        {"MAINT_AUTOMATE_NEUTRAL_ZONE",	8,-1},
        {"MAINT_NB_RESTRICT_VIT",	8,-1},
        {"MAINT_ID_RESTRICT_1",	8,-1},
        {"MAINT_DEBUT_1",	32,-1},
        {"MAINT_FIN_1",	32,-1},
        {"MAINT_VITESSE_1",	16,-1},
        {"MAINT_DELAI_1",	8,-1},
        {"MAINT_ID_RESTRICT_2",	8,-1},
        {"MAINT_DEBUT_2",	32,-1},
        {"MAINT_FIN_2",	32,-1},
        {"MAINT_VITESSE_2",	16,-1},
        {"MAINT_DELAI_2",	8,-1},
        {"MAINT_ID_RESTRICT_3",	8,-1},
        {"MAINT_DEBUT_3",	32,-1},
        {"MAINT_FIN_3",	32,-1},
        {"MAINT_VITESSE_3",	16,-1},
        {"MAINT_DELAI_3",	8,-1},
        {"MAINT_ID_RESTRICT_4",	8,-1},
        {"MAINT_DEBUT_4",	32,-1},
        {"MAINT_FIN_4",	32,-1},
        {"MAINT_VITESSE_4",	16,-1},
        {"MAINT_DELAI_4",	8,-1},
        {"MAINT_ID_RESTRICT_5",	8,-1},
        {"MAINT_DEBUT_5",	32,-1},
        {"MAINT_FIN_5",	32,-1},
        {"MAINT_VITESSE_5",	16,-1},
        {"MAINT_DELAI_5",	8,-1},
        {"MAINT_ID_RESTRICT_6",	8,-1},
        {"MAINT_DEBUT_6",	32,-1},
        {"MAINT_FIN_6",	32,-1},
        {"MAINT_VITESSE_6",	16,-1},
        {"MAINT_DELAI_6",	8,-1},
        {"MAINT_ID_RESTRICT_7",	8,-1},
        {"MAINT_DEBUT_7",	32,-1},
        {"MAINT_FIN_7",	32,-1},
        {"MAINT_VITESSE_7",	16,-1},
        {"MAINT_DELAI_7",	8,-1},
        {"MAINT_ID_RESTRICT_8",	8,-1},
        {"MAINT_DEBUT_8",	32,-1},
        {"MAINT_FIN_8",	32,-1},
        {"MAINT_VITESSE_8",	16,-1},
        {"MAINT_DELAI_8",	8,-1},
        {"MAINT_ID_RESTRICT_9",	8,-1},
        {"MAINT_DEBUT_9",	32,-1},
        {"MAINT_FIN_9",	32,-1},
        {"MAINT_VITESSE_9",	16,-1},
        {"MAINT_DELAI_9",	8,-1},
        {"MAINT_ID_RESTRICT_10",	8,-1},
        {"MAINT_DEBUT_10",	32,-1},
        {"MAINT_FIN_10",	32,-1},
        {"MAINT_VITESSE_10",	16,-1},
        {"MAINT_DELAI_10",	8,-1},
        {"MAINT_NB_VIT_MRSP",	8,-1},
        {"MAINT_DIST_1",	32,-1},
        {"MAINT_VIT_1",	16,-1},
        {"MAINT_DIST_2",	32,-1},
        {"MAINT_VIT_2",	16,-1},
        {"MAINT_DIST_3",	32,-1},
        {"MAINT_VIT_3",	16,-1},
        {"MAINT_DIST_4",	32,-1},
        {"MAINT_VIT_4",	16,-1},
        {"MAINT_DIST_5",	32,-1},
        {"MAINT_VIT_5",	16,-1},
        {"MAINT_DIST_6",	32,-1},
        {"MAINT_VIT_6",	16,-1},
        {"MAINT_DIST_7",	32,-1},
        {"MAINT_VIT_7",	16,-1},
        {"MAINT_DIST_8",	32,-1},
        {"MAINT_VIT_8",	16,-1},
        {"MAINT_DIST_9",	32,-1},
        {"MAINT_VIT_9",	16,-1},
        {"MAINT_DIST_10",	32,-1},
        {"MAINT_VIT_10",	16,-1},
        {"MAINT_NB_SSP",	8,-1},
        {"MAINT_FIN_SSP",	32,-1},
        {"MAINT_SSP_DIST_1",	32,-1},
        {"MAINT_SSP_VIT_1",	16,-1},
        {"MAINT_SSP_DIST_2",	32,-1},
        {"MAINT_SSP_VIT_2",	16,-1},
        {"MAINT_SSP_DIST_3",	32,-1},
        {"MAINT_SSP_VIT_3",	16,-1},
        {"MAINT_SSP_DIST_4",	32,-1},
        {"MAINT_SSP_VIT_4",	16,-1},
        {"MAINT_SSP_DIST_5",	32,-1},
        {"MAINT_SSP_VIT_5",	16,-1},
        {"MAINT_SSP_DIST_6",	32,-1},
        {"MAINT_SSP_VIT_6",	16,-1},
        {"MAINT_SSP_DIST_7",	32,-1},
        {"MAINT_SSP_VIT_7",	16,-1},
        {"MAINT_SSP_DIST_8",	32,-1},
        {"MAINT_SSP_VIT_8",	16,-1},
        {"MAINT_SSP_DIST_9",	32,-1},
        {"MAINT_SSP_VIT_9",	16,-1},
        {"MAINT_SSP_DIST_10",	32,-1},
        {"MAINT_SSP_VIT_10",	16,-1},
        {"MAINT_NB_PENTE",	8,-1},
        {"MAINT_PENTE_FIN",	32,-1},
        {"MAINT_PENTE_POS_1",	23,-1},
        {"MAINT_PENTE_GDIR_1",	1,-1},
        {"MAINT_PENTE_1",	8,-1},
        {"MAINT_PENTE_POS_2",	23,-1},
        {"MAINT_PENTE_GDIR_2",	1,-1},
        {"MAINT_PENTE_2",	8,-1},
        {"MAINT_PENTE_POS_3",	23,-1},
        {"MAINT_PENTE_GDIR_3",	1,-1},
        {"MAINT_PENTE_3",	8,-1},
        {"MAINT_PENTE_POS_4",	23,-1},
        {"MAINT_PENTE_GDIR_4",	1,-1},
        {"MAINT_PENTE_4",	8,-1},
        {"MAINT_PENTE_POS_5",	23,-1},
        {"MAINT_PENTE_GDIR_5",	1,-1},
        {"MAINT_PENTE_5",	8,-1},
        {"STATE_CONT_ERROR_GROUPES",	8,-1},
        {"PRE_ERROR_BG_NID_C",	16,-1},
        {"PRE_ERROR_BG_NID_BG",	16,-1},
        {"CUR_ERROR_BG_NID_C",	16,-1},
        {"CUR_ERROR_BG_NID_BG",	16,-1},
        {"LS_PADDING",	16,-1},
    },
    Detail_LS_Bistd[36]=
    {
        {"BISTD_ERTMS_FU_1",	1,-1},
        {"BISTD_ERTMS_FU_2",	1,-1},
        {"BISTD_ERTMS_FS",	1,-1},
        {"BISTD_ERTMS_DEFAUT_MINEUR",	1,-1},
        {"BISTD_ERTMS_DEFAUT_MAJEUR",	1,-1},
        {"BISTD_ERTMS_RESERVE",	11,-1},
        {"BISTD_CTCS_FU_1",	1,-1},
        {"BISTD_CTCS_FU_2",	1,-1},
        {"BISTD_CTCS_FS",	1,-1},
        {"BISTD_CTCS_DEFAUT_MINEUR",	1,-1},
        {"BISTD_CTCS_DEFAUT_MAJEUR",	1,-1},
        {"BISTD_CTCS_RESERVE",	11,-1},
        {"BISTD_SYNTHESE_FU_1",	1,-1},
        {"BISTD_SYNTHESE_FU_2",	1,-1},
        {"BISTD_SYNTHESE_FS",	1,-1},
        {"BISTD_SYNTHESE_DEFAUT_MINEUR",	1,-1},
        {"BISTD_SYNTHESE_DEFAUT_MAJEUR",	1,-1},
        {"BISTD_SYNTHESE_RESERVE",	11,-1},
        {"BISTD_ETAT_TIU_ERTMS",	8,-1},
        {"BISTD_ETAT_TIU_GENERAL",	8,-1},
        {"BISTD_ETAT_TIU_COMMUT",	8,-1},
        {"BISTD_ETAT_TIU_EB",	8,-1},
        {"BISTD_ETAT_TIU_SB_STRONG",	8,-1},
        {"BISTD_ETAT_TIU_SB",	8,-1},
        {"BISTD_ETAT_TIU_NEUTRAL_ZONE_STATE",	8,-1},
        {"BISTD_TEST_AVANT_DEPART_TVM",	1,-1},
        {"BISTD_QAR",	1,-1},
        {"BISTD_QAV",	1,-1},
        {"BISTD_RELECTURE_FU_1",	1,-1},
        {"BISTD_RELECTURE_FU_2",	1,-1},
        {"BISTD_RELECTURE_FS",	1,-1},
        {"BISTD_ISOLATION",	1,-1},
        {"BISTD_ENTREES_TIU_RESERVE",	9,-1},
        {"BISTD_ETAT_MODE_CTRL_ERTMS",	8,-1},
        {"BISTD_CODE_DEFAUT_MID",	8,-1},
        {"BISTD_PADDING",	16,-1},
    };
    struct
    {
        std::string ItemName;
        unsigned int ItemLength;
        qint64 value[3];
    }Detail_Ls_Ctcs[541]=
    {
    {"CTCS_L_GRADIENT",	32,{-1,-1,-1}},
           {"CTCS_L_SSP",	32,{-1,-1,-1}},
           {"CTCS_L_DEFINED_TRACK",	32,{-1,-1,-1}},
           {"CTCS_L_UNDEFINED_TRACK",	32,{-1,-1,-1}},
           {"CTCS_L_TSR",	32,{-1,-1,-1}},
           {"CTCS_CODE",	8,{-1,-1,-1}},
           {"CTCS_CARRIER",	8,{-1,-1,-1}},
           {"CTCS_CFSK_CODE",	8,{-1,-1,-1}},
           {"CTCS_CFSK_CARRIER",	8,{-1,-1,-1}},
           {"CTCS_TRAIN_LENGTH",	4,{-1,-1,-1}},
           {"CTCS_SOM_STATE",	4,{-1,-1,-1}},
           {"CTCS_DATA_RESERVE",	6,{-1,-1,-1}},
           {"CTCS_NO_CODE_TIMER_ACTIVED",	1,{-1,-1,-1}},
           {"CTCS_NO_CODE_TIME_OUT",	1,{-1,-1,-1}},
           {"CTCS_LOA_TSR_SET",	1,{-1,-1,-1}},
           {"CTCS_SET_ERTMS_TO_SF",	1,{-1,-1,-1}},
           {"CTCS_ERASE_ON_BOARD_DATA",	1,{-1,-1,-1}},
           {"CTCS_DEFINE_MA_FLAG",	1,{-1,-1,-1}},
           {"CTCS_ENTRY_TSR_ZONE",	1,{-1,-1,-1}},
           {"CTCS_TC_DEFINED",	1,{-1,-1,-1}},
           {"CTCS_GRADIENT_DEFINED",	1,{-1,-1,-1}},
           {"CTCS_SSP_DEFINED",	1,{-1,-1,-1}},
           {"CTCS_CARRIER_FREQUENCY_LOCKER",	8,{-1,-1,-1}},
           {"CTCS_AUTOMATICALLY_TRACK_SELECTED",	8,{-1,-1,-1}},
           {"CTCS_CURRENT_TRACK_SELECTED",	8,{-1,-1,-1}},
           {"CTCS_INCONSISTENT_LEVEL_MODE_COUNTER",	8,{-1,-1,-1}},
           {"CTCS_DRIVER_SELECT_PHASE",	8,{-1,-1,-1}},
           {"CTCS_EXTEND_OS_CTCS",	1,{-1,-1,-1}},
           {"CTCS_SOUND_QUEUE_FULL",	1,{-1,-1,-1}},
           {"CTCS_VOICE_QUEUE_FULL",	1,{-1,-1,-1}},
           {"CTCS_CIR_SEL_PHASE",	5,{-1,-1,-1}},
           {"CTCS_NID_NEXT_TSR",	8,{-1,-1,-1}},
           {"CTCS_EB",	1,{-1,-1,-1}},
           {"CTCS_MSB",	1,{-1,-1,-1}},
           {"CTCS_SB",	1,{-1,-1,-1}},
           {"CTCS_ERTMS_ITF_RESERVE_1",	5,{-1,-1,-1}},
           {"CTCS_MODE_SELECTED_BY_DRIVER",	8,{-1,-1,-1}},
           {"CTCS_DRIVER_SELECTION",	8,{-1,-1,-1}},
           {"CTCS_TRACK_SELECTED_BY_DRIVER",	8,{-1,-1,-1}},
           {"CTCS_LEVEL_SELECTED_BY_DRIVER",	8,{-1,-1,-1}},
           {"CTCS_CAB_SIGNAL",	8,{-1,-1,-1}},
           {"CTCS_Text_Code",	8,{-1,-1,-1}},
           {"CTCS_RECEIVED_CTCS_PACKET_1",	1,{-1,-1,-1}},
           {"CTCS_RECEIVED_CTCS_PACKET_2",	1,{-1,-1,-1}},
           {"CTCS_RECEIVED_CTCS_PACKET_3",	1,{-1,-1,-1}},
           {"CTCS_RECEIVED_CTCS_PACKET_4",	1,{-1,-1,-1}},
           {"CTCS_RECEIVED_CTCS_PACKET_5",	1,{-1,-1,-1}},
           {"CTCS_RECEIVED_CTCS_PACKET_41",	1,{-1,-1,-1}},
           {"CTCS_RESERVE_ETCS_ITF_1",	2,{-1,-1,-1}},
           {"CTCS_D_EOA",	32,{-1,-1,-1}},
           {"CTCS_D_MA",	32,{-1,-1,-1}},
           {"CTCS_V_MA",	16,{-1,-1,-1}},
           {"CTCS_D_SR_ALLOC",	32,{-1,-1,-1}},
           {"CTCS_V_SR_ALLOC",	16,{-1,-1,-1}},
           {"CTCS_CTCS_MODE",	8,{-1,-1,-1}},
           {"CTCS_TRANSITION_CONDITION",	8,{-1,-1,-1}},
           {"CTCS_D_END_ONSIGHT",	32,{-1,-1,-1}},
           {"CTCS_V_ENTRY_TSR",	16,{-1,-1,-1}},
           {"CTCS_V_EXIT_TSR",	16,{-1,-1,-1}},
           {"CTCS_ENTRY_TSR_ACTIVE",	1,{-1,-1,-1}},
           {"CTCS_EXIT_TSR_ACTIVE",	1,{-1,-1,-1}},
           {"SOM_WITH_PS4_WHEN_RESTRICT_CODE",	1,{-1,-1,-1}},
           {"EXECUTE_SIDING_PROTECTION",	1,{-1,-1,-1}},
           {"LEU_DEFAULT_PROTECTION",	1,{-1,-1,-1}},
           {"HIGH_SPEED_PS2_MODE",	1,{-1,-1,-1}},
           {"CTCS_RESERVE_MODE_MGR_1",	2,{-1,-1,-1}},
           {"CTCS_TRACK_SELECTED_AUTOMATICALLY",	8,{-1,-1,-1}},
           {"CTCS_ENTER_NEW_SECTION",	8,{-1,-1,-1}},
           {"CTCS_COUNT_SECTIONS",	8,{-1,-1,-1}},
           {"CTCS_SECTION_NID_SIGNAL_1",	8,{-1,-1,-1}},
           {"CTCS_SECTION_NID_FREQUENCY_1",	8,{-1,-1,-1}},
           {"CTCS_SECTION_D_START_1",	32,{-1,-1,-1}},
           {"CTCS_SECTION_D_END_1",	32,{-1,-1,-1}},
           {"CTCS_SECTION_NID_SIGNAL_2",	8,{-1,-1,-1}},
           {"CTCS_SECTION_NID_FREQUENCY_2",	8,{-1,-1,-1}},
           {"CTCS_SECTION_D_START_2",	32,{-1,-1,-1}},
           {"CTCS_SECTION_D_END_2",	32,{-1,-1,-1}},
           {"CTCS_SECTION_NID_SIGNAL_3",	8,{-1,-1,-1}},
           {"CTCS_SECTION_NID_FREQUENCY_3",	8,{-1,-1,-1}},
           {"CTCS_SECTION_D_START_3",	32,{-1,-1,-1}},
           {"CTCS_SECTION_D_END_3",	32,{-1,-1,-1}},
           {"CTCS_SECTION_NID_SIGNAL_4",	8,{-1,-1,-1}},
           {"CTCS_SECTION_NID_FREQUENCY_4",	8,{-1,-1,-1}},
           {"CTCS_SECTION_D_START_4",	32,{-1,-1,-1}},
           {"CTCS_SECTION_D_END_4",	32,{-1,-1,-1}},
           {"CTCS_SECTION_NID_SIGNAL_5",	8,{-1,-1,-1}},
           {"CTCS_SECTION_NID_FREQUENCY_5",	8,{-1,-1,-1}},
           {"CTCS_SECTION_D_START_5",	32,{-1,-1,-1}},
           {"CTCS_SECTION_D_END_5",	32,{-1,-1,-1}},
           {"CTCS_TVM_ARMING_RESEARCH_TYPE",	8,{-1,-1,-1}},
           {"CTCS_TVM_ARMING_TRACK",	8,{-1,-1,-1}},
           {"CTCS_TVM_MODULATION_ANALYSIS",	8,{-1,-1,-1}},
           {"CTCS_TVM_ARMING_SIGNALING",	8,{-1,-1,-1}},
           {"CTCS_TVM_INHIBITION_CRN_ERRORS",	1,{-1,-1,-1}},
           {"CTCS_TVM_RESERVE_SIGNALLING",	7,{-1,-1,-1}},
           {"CTCS_TVM_RELEASE_BRAKE",	1,{-1,-1,-1}},
           {"CTCS_TVM_ASM_OVERPASS",	1,{-1,-1,-1}},
           {"CTCS_TVM_RESERVE_DMI",	6,{-1,-1,-1}},
           {"CTCS_TVM_YEAR",	8,{-1,-1,-1}},
           {"CTCS_TVM_MONTH",	8,{-1,-1,-1}},
           {"CTCS_TVM_DAY",	8,{-1,-1,-1}},
           {"CTCS_TVM_HOUR",	8,{-1,-1,-1}},
           {"CTCS_TVM_MINUTE",	8,{-1,-1,-1}},
           {"CTCS_TVM_SECOND",	8,{-1,-1,-1}},
           {"CTCS_TVM_MILLISECOND",	16,{-1,-1,-1}},
           {"CTCS_TVM_INFO_AVAILABLE",	1,{-1,-1,-1}},
           {"CTCS_TVM_RESERVE_DATE",	7,{-1,-1,-1}},
           {"TVM_CTCS_FLAG_JOINT",	1,{-1,-1,-1}},
           {"TVM_CTCS_FLAG_NEW_SPEED_RATE",	1,{-1,-1,-1}},
           {"TVM_CTCS_RESERVE_SIGNALLING",	6,{-1,-1,-1}},
           {"TVM_CTCS_ARMING_TRACK_TYPE",	8,{-1,-1,-1}},
           {"TVM_CTCS_CARRIER_FREQUENCY",	8,{-1,-1,-1}},
           {"TVM_CTCS_MODULATION_ANALYSIS",	8,{-1,-1,-1}},
           {"TVM_CTCS_SPEED_RATE",	8,{-1,-1,-1}},
           {"TVM_CTCS_ANALYSIS_ERROR",	8,{-1,-1,-1}},
           {"TVM_CTCS_TARGET_SPEED",	32,{-1,-1,-1}},
           {"TVM_CTCS_PERMITTED_SPEED",	32,{-1,-1,-1}},
           {"TVM_CTCS_WARNING_SPEED",	32,{-1,-1,-1}},
           {"TVM_CTCS_INTERVENTION_SPEED",	32,{-1,-1,-1}},
           {"TVM_CTCS_RELEASE_SPEED",	32,{-1,-1,-1}},
           {"TVM_CTCS_DISTANCE_TO_TARGET",	32,{-1,-1,-1}},
           {"TVM_CTCS_TARGET_SPEED_CHANGE",	8,{-1,-1,-1}},
           {"TVM_CTCS_TARGET_SPEED_NATURE",	8,{-1,-1,-1}},
           {"TVM_CTCS_DISPLAY_DIST_TO_TARGET",	1,{-1,-1,-1}},
           {"TVM_CTCS_SPEED_WARNING",	1,{-1,-1,-1}},
           {"TVM_CTCS_BRAKE_RELEASABLE",	1,{-1,-1,-1}},
           {"TVM_CTCS_ASM_EB",	1,{-1,-1,-1}},
           {"TVM_CTCS_ASM_OVERPASS_AUTHORIZED",	1,{-1,-1,-1}},
           {"TVM_CTCS_ASM_OVERPASS_FORBIDDEN",	1,{-1,-1,-1}},
           {"TVM_CTCS_RESERVE_DMI",	2,{-1,-1,-1}},
           {"CTCS_D_REVERSE_SECTION",	32,{-1,-1,-1}},
           {"CTCS_D_END_REVERSE_SECTION",	32,{-1,-1,-1}},
           {"CTCS_D_BIG_NUMBER_POINT",	32,{-1,-1,-1}},
           {"CTCS_V_UUS_EXIT_SPEED",	32,{-1,-1,-1}},
           {"CTCS_NID_MESSAGE_TO_LKJ",	8,{-1,-1,-1}},
           {"CTCS_L_MESSAGE_TO_LKJ",	10,{-1,-1,-1}},
           {"CTCS_YEAR_TO_LKJ",	7,{-1,-1,-1}},
           {"CTCS_MONTH_TO_LKJ",	4,{-1,-1,-1}},
           {"CTCS_DAY_TO_LKJ",	5,{-1,-1,-1}},
           {"CTCS_HOUR_TO_LKJ",	5,{-1,-1,-1}},
           {"CTCS_MINUTES_TO_LKJ",	6,{-1,-1,-1}},
           {"CTCS_SECONDS_TO_LKJ",	6,{-1,-1,-1}},
           {"CTCS_TTS_TO_LKJ",	5,{-1,-1,-1}},
           {"CTCS_STATUS_TO_LKJ",	4,{-1,-1,-1}},
           {"CTCS_LKJ_Q_SCALE",	2,{-1,-1,-1}},
           {"CTCS_ID_REGION",	10,{-1,-1,-1}},
           {"CTCS_ID_ETCS",	14,{-1,-1,-1}},
           {"CTCS_D_LRBG",	15,{-1,-1,-1}},
           {"CTCS_Q_DIR_LRBG",	2,{-1,-1,-1}},
           {"CTCS_Q_DLRBG",	2,{-1,-1,-1}},
           {"CTCS_V_TRAIN",	16,{-1,-1,-1}},
           {"CTCS_V_LIMIT_SPEED",	16,{-1,-1,-1}},
           {"CTCS_V_TARGET",	16,{-1,-1,-1}},
           {"CTCS_LEVEL",	3,{-1,-1,-1}},
           {"CTCS_MODE",	4,{-1,-1,-1}},
           {"CTCS_CAB_SIGNAL_CODE",	5,{-1,-1,-1}},
           {"CTCS_CAB_SIGNAL_SPEED",	3,{-1,-1,-1}},
           {"CTCS_NID_JOINT",	8,{-1,-1,-1}},
           {"CTCS_NID_MESSAGE_FROM_LKJ",	8,{-1,-1,-1}},
           {"CTCS_L_MESSAGE_FROM_LKJ",	10,{-1,-1,-1}},
           {"CTCS_YEAR_FROM_LKJ",	7,{-1,-1,-1}},
           {"CTCS_MONTH_FROM_LKJ",	4,{-1,-1,-1}},
           {"CTCS_DAY_FROM_LKJ",	5,{-1,-1,-1}},
           {"CTCS_HOUR_FROM_LKJ",	5,{-1,-1,-1}},
           {"CTCS_MINUTES_FROM_LKJ",	6,{-1,-1,-1}},
           {"CTCS_SECONDS_FROM_LKJ",	6,{-1,-1,-1}},
           {"CTCS_TTS_FROM_LKJ",	5,{-1,-1,-1}},
           {"CTCS_STATUS_FROM_LKJ",	4,{-1,-1,-1}},
           {"CTCS_LANGUAGE_ID",	6,{-1,-1,-1}},
           {"CTCS_COMPANY_ID",	10,{-1,-1,-1}},
           {"CTCS_DRIVER_ID_1",	16,{-1,-1,-1}},
           {"CTCS_DRIVER_ID_2",	16,{-1,-1,-1}},
           {"CTCS_LETTER_CODE_1",	8,{-1,-1,-1}},
           {"CTCS_LETTER_CODE_2",	8,{-1,-1,-1}},
           {"CTCS_LETTER_CODE_3",	8,{-1,-1,-1}},
           {"CTCS_DIGIT_CODE_1",	4,{-1,-1,-1}},
           {"CTCS_DIGIT_CODE_2",	4,{-1,-1,-1}},
           {"CTCS_DIGIT_CODE_3",	4,{-1,-1,-1}},
           {"CTCS_DIGIT_CODE_4",	4,{-1,-1,-1}},
           {"CTCS_DIGIT_CODE_5",	4,{-1,-1,-1}},
           {"CTCS_Q_POWERCUTOFF",	1,{-1,-1,-1}},
           {"CTCS_Q_SB",	3,{-1,-1,-1}},
           {"CTCS_Q_EB",	1,{-1,-1,-1}},
           {"CTCS_RESERVE",	3,{-1,-1,-1}},
           {"CTCS_STATE",	2,{-1,-1,-1}},
           {"CTCS_RESERVE2",	6,{-1,-1,-1}},
           {"LKJ_STATE_CFG",	16,{-1,-1,-1}},
           {"CTCS_LEVEL_MANAGER_STATE",	8,{-1,-1,-1}},
           {"CTCS_LKJ_BRAKING",	1,{-1,-1,-1}},
           {"CTCS_ATP_BRAKING",	1,{-1,-1,-1}},
           {"CTCS_LEVEL_MANAGER_RESERVE",	6,{-1,-1,-1}},
           {"CTCS_D_TRANSITION_ANNOUNCE_LOCATION",	32,{-1,-1,-1}},
           {"CTCS_LEVEL_ANNOUNCED",	8,{-1,-1,-1}},
           {"CTCS_D_TRANSITION_EXECUTED_AT",	32,{-1,-1,-1}},
           {"CTCS_LEVEL_EXECUTED",	8,{-1,-1,-1}},
           {"CTCS_CTCS_PRIORITY",	8,{-1,-1,-1}},
           {"CTCS_Cfsk_Redundancy_State",	2,{-1,-1,-1}},
           {"CTCS_Cfsk_Chosen_Link_Cfg",	2,{-1,-1,-1}},
           {"CTCS_Cfsk_Chosen_Link_App",	2,{-1,-1,-1}},
           {"CTCS_CFSK_A_Msg_State",	2,{-1,-1,-1}},
           {"CTCS_CFSK_B_Msg_State",	2,{-1,-1,-1}},
           {"CTCS_CFSK_A_Decode_Ok",	1,{-1,-1,-1}},
           {"CTCS_CFSK_B_Decode_Ok",	1,{-1,-1,-1}},
           {"CTCS_Cfsk_Msg_State_reserve",	4,{-1,-1,-1}},
           {"CTCS_CFSK_Message_Id",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Msg_Length",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Seq_Number",	16,{-1,-1,-1}},
           {"CTCS_Allowed_Freq",	3,{-1,-1,-1}},
           {"CTCS_ALLOWED_FREQ_Reserve",	5,{-1,-1,-1}},
           {"CTCS_Cfsk_Cpu_Self_Test_OK",	1,{-1,-1,-1}},
           {"CTCS_Cfsk_Ram_Self_Test_OK",	1,{-1,-1,-1}},
           {"CTCS_Cfsk_Rom_Checksum_OK",	1,{-1,-1,-1}},
           {"CTCS_Cfsk_Atp_Configuration_Reserve",	5,{-1,-1,-1}},
           {"CTCS_CFSK_Current_Mode_A",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Fast_Carrier_Freq_A",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Code_Acf_A",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Code_Low_Freq_A",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Code_Amplitude_A",	16,{-1,-1,-1}},
           {"CTCS_CFSK_Current_Mode_B",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Fast_Carrier_Freq_B",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Code_Acf_B",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Code_Low_Freq_B",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Code_Amplitude_B",	16,{-1,-1,-1}},
           {"CTCS_CFSK_Joint_Id",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Error",	8,{-1,-1,-1}},
           {"CTCS_CFSK_Maintain_Data",	32,{-1,-1,-1}},
           {"CTCS_CTCS_EQPT_STATE",	8,{-1,-1,-1}},
           {"CTCS_D_MIN",	32,{-1,-1,-1}},
           {"CTCS_D_MAX",	32,{-1,-1,-1}},
           {"CTCS_FREQUENCY_CONSISTENT",	1,{-1,-1,-1}},
           {"CTCS_FREQ_RES_RESERVE",	7,{-1,-1,-1}},
           {"CTCS_CURRENT_LEVEL",	8,{-1,-1,-1}},
           {"CTCS_STM_MASTER_ERTMS",	8,{-1,-1,-1}},
           {"CTCS_MANIP_TRACTION",	8,{-1,-1,-1}},
           {"CTCS_ISOLATION",	1,{-1,-1,-1}},
           {"CTCS_INFO_FU_FS_LKJ",	1,{-1,-1,-1}},
           {"CTCS_FS_ED",	1,{-1,-1,-1}},
           {"CTCS_RESERVE_TIU_IN",	5,{-1,-1,-1}},
           {"CTCS_SYSTEM_ACTIF",	8,{-1,-1,-1}},
           {"CTCS_FS_FAIBLE",	1,{-1,-1,-1}},
           {"CTCS_FS_MOYEN",	1,{-1,-1,-1}},
           {"CTCS_RESERVE_TIU_OUT",	6,{-1,-1,-1}},
           {"CTCS_BACK_SLIDE_TIME",	16,{-1,-1,-1}},
           {"CTCS_BACK_SLIDE_TRACTION",	8,{-1,-1,-1}},
           {"CTCS_BACK_SLIDE_IS_TRIGGERED",	1,{-1,-1,-1}},
           {"CTCS_BACK_SLIDE_RESERVE",	7,{-1,-1,-1}},
           {"CTCS_ERROR_IS_RAISED",	16,{-1,-1,-1}},
           {"CTCS_ERROR_PACKAGE_NAME",	8,{-1,-1,-1}},
           {"CTCS_ERROR_METHOD_NAME",	1,{-1,-1,-1}},
           {"CTCS_ERROR_VARIABLE_NAME",	7,{-1,-1,-1}},
           {"CTCS_MACHINE_PRIORITY_CMD_SPEED",	16,{-1,-1,-1}},
           {"CTCS_MACHINE_PRIORITY_CMD_SPEED_ESTIMATED",	16,{-1,-1,-1}},
           {"CTCS_MACHINE_PRIORITY_CURRENT_THRESHOLD",	16,{-1,-1,-1}},
           {"CTCS_MACHINE_PRIORITY_AUTOMAT",	8,{-1,-1,-1}},
           {"CTCS_MACHINE_PRIORITY_CURRENT_BRAKE_CMD",	8,{-1,-1,-1}},
           {"DRIVER_SELECTION",	8,{-1,-1,-1}},
           {"DMI_NEW_MSG_MENU",	1,{-1,-1,-1}},
           {"DMI_DISPLAY_MENU",	5,{-1,-1,-1}},
           {"DMI_REVERS2",	2,{-1,-1,-1}},
           {"DRIVER_ACK_MSG_ID",	8,{-1,-1,-1}},
           {"AUTOMATE_NO_CODE_TOLERANCE_TIME",	8,{-1,-1,-1}},
           {"NEXT_CARRY_FREQUENCY_FORECAST",	8,{-1,-1,-1}},
           {"AUTOMATE_NO_CODE_TREATMENT",	8,{-1,-1,-1}},
           {"RESERVE_NO_CODE_TREATMENT",	8,{-1,-1,-1}},
           {"AUTOMATE_STANDSTILL_PROTECT",	8,{-1,-1,-1}},
           {"RESERVE_STANDSTILL_PROTECT",	8,{-1,-1,-1}},//{"UPDATE_METHOD",	8,{-1,-1,-1}},
           {"CURRENT_LANGUAGE_ID",	6,{-1,-1,-1}},
           {"CURRENT_COMPANY_ID",	10,{-1,-1,-1}},
           {"CURRENT_DRIVER_ID_1",	16,{-1,-1,-1}},
           {"CURRENT_DRIVER_ID_2",	16,{-1,-1,-1}},
           {"CURRENT_LETTER_CODE_1",	8,{-1,-1,-1}},
           {"CURRENT_LETTER_CODE_2",	8,{-1,-1,-1}},
           {"CURRENT_LETTER_CODE_3",	8,{-1,-1,-1}},
           {"CURRENT_LETTER_CODE_4",	8,{-1,-1,-1}},
           {"CURRENT_DIGIT_CODE_1",	4,{-1,-1,-1}},
           {"CURRENT_DIGIT_CODE_2",	4,{-1,-1,-1}},
           {"CURRENT_DIGIT_CODE_3",	4,{-1,-1,-1}},
           {"CURRENT_DIGIT_CODE_4",	4,{-1,-1,-1}},
           {"CURRENT_DIGIT_CODE_5",	4,{-1,-1,-1}},/**********以下更改了******/
           {"DRIVER_ID_SOURCE",	2,{-1,-1,-1}},
           {"MISSION_ID_SOURCE",	2,{-1,-1,-1}},
           {"DRIVER_ID_SEND_TO_LKJ",	1,{-1,-1,-1}},
           {"DRIVER_ID_SEND_TO_DMI",	1,{-1,-1,-1}},
           {"MISSION_ID_SEND_TO_LKJ",	1,{-1,-1,-1}},
           {"MISSION_ID_SEND_TO_DMI",	1,{-1,-1,-1}},
           {"RESERVE_MISSION_DATA",	20,{-1,-1,-1}},
    {"BUTTON_TO_BE_CONFIRMED",	8,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_DATA",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_MODE",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_DIRECTION",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_LEVEL",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_START",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_RELEASE",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_ACKNOWLEDGE",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TRAIN_MISSION",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_OS",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_SH",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_END_OF_MISSION",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_EXTI_SH",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_PS",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_VERSION",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TRACK_UP",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TRACK_DOWN",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_CTCS0",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_CTCS1",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_CTCS2",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_CS",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_BACK",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TRAIN_LENGTH",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_SINGLE_TRAIN_LENGTH",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_DOUBLE_TRAIN_LENGTH",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_DATE_TIME",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_DMI_TEST",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_OTHER_TRAIN_LENGTH",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TRAIN_MISSION_OVERPASS",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TRAIN_MISSION_VALIDATED",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_OTHER_OPTION",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TEST_WATCH_DOG",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TEST_SAFTY",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_TEST_VRAM",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_BRIGHTNESS",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_VOLUME",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_LANGUAGE",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_ENSURE",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_CANCEL",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_BRAKE_TEST",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_EB_TEST",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_MSB_TEST",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_DRIVER_ID",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_DRIVER_ID_VALIDATED",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_MISSION_ID",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_MISSION_ID_VALIDATED",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_CCS_DATA",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_BTM_SELECT",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_BTM1",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_BTM2",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_ATO_ALLOW",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_PRESELECT_ATO",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_PRESELECT_WITH_ATO",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_PRESELECT_NONE_ATO",	1,{-1,-1,-1}},
    {"BUTTON_AVAILABLE_RESERVE",	11,{-1,-1,-1}},
    {"Brake_Release_Asked_By_Driver",	8,{-1,-1,-1}},
    {"Brake_Test_State",	8,{-1,-1,-1}},
    {"State_Automatically",	8,{-1,-1,-1}},
    {"State_Manually",	8,{-1,-1,-1}},
    {"Model_Brake_Test_Auto",	8,{-1,-1,-1}},
    {"EB_Test_Automatically",	8,{-1,-1,-1}},
    {"MSB_Test_Automatically",	8,{-1,-1,-1}},
    {"Model_Brake_Test_Manually",	8,{-1,-1,-1}},
    {"EB_Test_Manually",	8,{-1,-1,-1}},
    {"MSB_Test_Manually",	8,{-1,-1,-1}},
    {"CTCS_START_EB_TEST_MANUALLY",	1,{-1,-1,-1}},
    {"CTCS_START_MSB_TEST_MANUALLY",	1,{-1,-1,-1}},
    {"CTCS_BRAKE_TEST_MANUALLY_COMPLETED",	1,{-1,-1,-1}},
    {"Brake_Releasable",	1,{-1,-1,-1}},
    {"Brake_Released_By_Driver",	1,{-1,-1,-1}},
    {"EB_Test_Manually_Complete",	1,{-1,-1,-1}},
    {"MSB_Test_Manually_Complete",	1,{-1,-1,-1}},
    {"Brake_Reserve",	1,{-1,-1,-1}},
    {"MSB_No_Reason_Braking",	1,{-1,-1,-1}},
    {"MSB_No_Reason_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_No_Reason_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Frequency_Inconsistency_Braking",	1,{-1,-1,-1}},
    {"MSB_Frequency_Inconsistency_Release_Requs",	1,{-1,-1,-1}},
    {"MSB_Frequency_Inconsistency_Release_Typest",	2,{-1,-1,-1}},
    {"MSB_Nocode_In_PS_Braking",	1,{-1,-1,-1}},
    {"MSB_Nocode_In_PS_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Nocode_In_PS_Release_Type",	2,{-1,-1,-1}},
    {"MSB_NoCode_In_FS_Braking",	1,{-1,-1,-1}},
    {"MSB_NoCode_In_FS_Release_Request",	1,{-1,-1,-1}},
    {"MSB_NoCode_In_FS_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Transition_PS_CO_Braking",	1,{-1,-1,-1}},
    {"MSB_Transition_PS_CO_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Transition_PS_CO_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Transition_FS_PS_Braking",	1,{-1,-1,-1}},
    {"MSB_Transition_FS_PS_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Transition_FS_PS_Release_Type",	2,{-1,-1,-1}},
    {"MSB_PS_Mode_Received_HU_Braking",	1,{-1,-1,-1}},
    {"MSB_PS_Mode_Received_HU_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_PS_Mode_Received_HU_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Siding_Bg_Pt_Braking",	1,{-1,-1,-1}},
    {"MSB_Siding_Bg_Pt_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Siding_Bg_Pt_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Siding_Tc_Pt_Braking",	1,{-1,-1,-1}},
    {"MSB_Siding_Tc_Pt_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Siding_Tc_Pt_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Default_Telegram_Braking",	1,{-1,-1,-1}},
    {"MSB_Default_Telegram_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Default_Telegram_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Cont_Bg_Error_Braking",	1,{-1,-1,-1}},
    {"MSB_Cont_Bg_Error_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Cont_Bg_Error_Release_Type",	2,{-1,-1,-1}},
    {"MSB_NoCode_Outdistance_In_PS_Braking",	1,{-1,-1,-1}},
    {"MSB_NoCode_Outdistance_In_PS_Release_Requ",	1,{-1,-1,-1}},
    {"MSB_NoCode_Outdistance_In_Release_Typeust",	2,{-1,-1,-1}},
    {"MSB_FS_Tsr_Exhaust_Braking",	1,{-1,-1,-1}},
    {"MSB_FS_Tsr_Exhaust_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_FS_Tsr_Exhaust_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Lrbg_More_Than_5Km_Braking",	1,{-1,-1,-1}},
    {"MSB_Lrbg_More_Than_5Km_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Lrbg_More_Than_5Km_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Test_Braking",	1,{-1,-1,-1}},
    {"MSB_Test_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Test_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Sf_Braking",	1,{-1,-1,-1}},
    {"MSB_Sf_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Sf_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Curve_Braking",	1,{-1,-1,-1}},
    {"MSB_Curve_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Curve_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Link_Reaction_Braking",	1,{-1,-1,-1}},
    {"MSB_Link_Reaction_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Link_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Roll_Away_Braking",	1,{-1,-1,-1}},
    {"MSB_Roll_Away_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Roll_Away_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Reverse_Movement_Braking",	1,{-1,-1,-1}},
    {"MSB_Reverse_Movement_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Reverse_Movement_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Brake_Compatible_Braking",	1,{-1,-1,-1}},
    {"MSB_Brake_Compatible_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Brake_Compatible_Release_Type",	2,{-1,-1,-1}},
    {"MSB_SB1_Braking",	1,{-1,-1,-1}},
    {"MSB_SB1_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_SB1_Release_Type",	2,{-1,-1,-1}},
    {"MSB_SB2_Braking",	1,{-1,-1,-1}},
    {"MSB_SB2_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_SB2_Release_Type",	2,{-1,-1,-1}},
    {"MSB_SB3_Braking",	1,{-1,-1,-1}},
    {"MSB_SB3_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_SB3_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Self_Test_Braking",	1,{-1,-1,-1}},
    {"MSB_Self_Test_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Self_Test_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Text_Not_Acknowledged_Braking",	1,{-1,-1,-1}},
    {"MSB_Text_Not_Acknowledged_Release_Requst",	1,{-1,-1,-1}},
    {"MSB_Text_Not_Acknowledged_Release_Type",	2,{-1,-1,-1}},
    {"MSB_Notify_Reserve",	152,{-1,-1,-1}},
    {"TR_No_Reason_Braking",	1,{-1,-1,-1}},
    {"TR_No_Reason_Release_Requst",	1,{-1,-1,-1}},
    {"TR_No_Reason_Release_Type",	2,{-1,-1,-1}},
    {"TR_Link_Reaction_Braking",	1,{-1,-1,-1}},
    {"TR_Link_Reaction_Release_Requst",	1,{-1,-1,-1}},
    {"TR_Link_Reaction_Release_Type",	2,{-1,-1,-1}},
    {"TR_Reception_H_Braking",	1,{-1,-1,-1}},
    {"TR_Reception_H_Release_Requst",	1,{-1,-1,-1}},
    {"TR_Reception_H_Release_Type",	2,{-1,-1,-1}},
    {"TR_Emergency_Stop_Braking",	1,{-1,-1,-1}},
    {"TR_Emergency_Stop_Release_Requst",	1,{-1,-1,-1}},
    {"TR_Emergency_Stop_Release_Type",	2,{-1,-1,-1}},
    {"TR_SH_Not_Authorized_Braking",	1,{-1,-1,-1}},
    {"TR_SH_Not_Authorized_Release_Requst",	1,{-1,-1,-1}},
    {"TR_SH_Not_Authorized_Release_Type",	2,{-1,-1,-1}},
    {"TR_Curve_Braking",	1,{-1,-1,-1}},
    {"TR_Curve_Release_Requst",	1,{-1,-1,-1}},
    {"TR_Curve_Release_Type",	2,{-1,-1,-1}},
    {"EB_No_Reason_Braking",	1,{-1,-1,-1}},
    {"EB_No_Reason_Release_Requst",	1,{-1,-1,-1}},
    {"EB_No_Reason_Release_Type",	2,{-1,-1,-1}},
    {"EB_Backslide_Braking",	1,{-1,-1,-1}},
    {"EB_Backslide_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Backslide_Release_Type",	2,{-1,-1,-1}},
    {"EB_Not_Extend_Ma_In_OS_Braking",	1,{-1,-1,-1}},
    {"EB_Not_Extend_Ma_In_OS_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Not_Extend_Ma_In_OS_Release_Type",	2,{-1,-1,-1}},
    {"EB_Not_Extend_Ma_In_CO_Braking",	1,{-1,-1,-1}},
    {"EB_Not_Extend_Ma_In_CO_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Not_Extend_Ma_In_CO_Release_Type",	2,{-1,-1,-1}},
    {"EB_MSB_Reread_Default_Braking",	1,{-1,-1,-1}},
    {"EB_MSB_Reread_Default_Release_Requst",	1,{-1,-1,-1}},
    {"EB_MSB_Reread_Default_Release_Type",	2,{-1,-1,-1}},
    {"EB_Test_Braking",	1,{-1,-1,-1}},
    {"EB_Test_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Test_Release_Type",	2,{-1,-1,-1}},
    {"EB_Test_EB1_Braking",	1,{-1,-1,-1}},
    {"EB_Test_EB1_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Test_EB1_Release_Type",	2,{-1,-1,-1}},
    {"EB_Test_EB2_Braking",	1,{-1,-1,-1}},
    {"EB_Test_EB2_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Test_EB2_Release_Type",	2,{-1,-1,-1}},
    {"EB_Sf_Braking",	1,{-1,-1,-1}},
    {"EB_Sf_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Sf_Release_Type",	2,{-1,-1,-1}},
    {"EB_Curve_Braking",	1,{-1,-1,-1}},
    {"EB_Curve_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Curve_Release_Type",	2,{-1,-1,-1}},
    {"EB_Roll_Away_Braking",	1,{-1,-1,-1}},
    {"EB_Roll_Away_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Roll_Away_Release_Type",	2,{-1,-1,-1}},
    {"EB_Reverse_Movement_Braking",	1,{-1,-1,-1}},
    {"EB_Reverse_Movement_Release_Requst",	1,{-1,-1,-1}},
    {"EB_Reverse_Movement_Release_Type",	2,{-1,-1,-1}},
    {"EB_Notify_Reserve",	184,{-1,-1,-1}},
    {"Timer_Freq_Inconsistent",	16,{-1,-1,-1}},
    {"Timer_Freq_Inconsistent_Active",	8,{-1,-1,-1}},
    {"Timer_No_Code_After_HU",	16,{-1,-1,-1}},
    {"Timer_No_Code_After_HU_Active",	8,{-1,-1,-1}},
    {"Timer_RV_Or_CL_As_No_Code",	16,{-1,-1,-1}},
    {"Timer_RV_Or_CL_As_No_Code_Active",	8,{-1,-1,-1}},
    {"Timer_Brake_Test",	16,{-1,-1,-1}},
    {"Timer_Brake_Test_Active",	8,{-1,-1,-1}},
    {"Timer_Brake_Test_Margin",	16,{-1,-1,-1}},
    {"Timer_Brake_Test_Margin_Active",	8,{-1,-1,-1}},
    {"Timer_Extend_Ma_Alarm",	16,{-1,-1,-1}},
    {"Timer_Extend_Ma_Alarm_Active",	8,{-1,-1,-1}},
    {"Timer_Extend_Ma_Trigger_EB",	16,{-1,-1,-1}},
    {"Timer_Extend_Ma_Trigger_EB_Active",	8,{-1,-1,-1}},
    {"Timer_Mission_Date_Switch",	16,{-1,-1,-1}},
    {"Timer_Mission_Date_Switch_Active",	8,{-1,-1,-1}},
    {"Timer_Lkj_Failure_Dmi_Msg",	16,{-1,-1,-1}},
    {"Timer_Lkj_Failure_Dmi_Msg_Active",	8,{-1,-1,-1}},
    {"Timer_Back_Slide",	16,{-1,-1,-1}},
    {"Timer_Back_Slide_Active",	8,{-1,-1,-1}},
    {"Timer_Reserve",	96,{-1,-1,-1}},
    {"State_No_Code_Movement",	8,{-1,-1,-1}},
    {"State_Set_Loa_For_F0000_Section",	8,{-1,-1,-1}},
    {"Set_Loa_F0000",	8,{-1,-1,-1}},
    {"State_Bg_Protect",	8,{-1,-1,-1}},
    {"State_Siding_Route",	8,{-1,-1,-1}},
    {"Defualt_Teleg_Protection",	1,{-1,-1,-1}},
    {"Debut_Siding",	1,{-1,-1,-1}},
    {"Route_Pt_Reserve",	6,{-1,-1,-1}},
    {"Turnout_Loa_D_Tsr",	32,{-1,-1,-1}},
    {"Turnout_Loa_L_Tsr",	32,{-1,-1,-1}},
    {"Turnout_Loa_V_Tsr",	16,{-1,-1,-1}},
    {"Station_Loa_D_Tsr",	32,{-1,-1,-1}},
    {"Station_Loa_L_Tsr",	32,{-1,-1,-1}},
    {"Station_Loa_V_Tsr",	16,{-1,-1,-1}},
    {"Big_Num_Point_Available",	1,{-1,-1,-1}},
    {"Set_Big_Num_Point",	1,{-1,-1,-1}},
    {"Reserve_Turnout_Pt",	14,{-1,-1,-1}},
    {"CFSK_TC_CODE",	8,{-1,-1,-1}},
    {"CAB_DISPLAY_TO_DMI",	8,{-1,-1,-1}},
    {"PRE_CAB_DISPLAY",	8,{-1,-1,-1}},
    {"RESERVE_CAB_DISPLAY",	8,{-1,-1,-1}},
    {"New_Station_Side_Info",	1,{-1,-1,-1}},
    {"Station_Side_Dir",	2,{-1,-1,-1}},
    {"Reverse",	5,{-1,-1,-1}},
    {"Station_Side_D_Start",	32,{-1,-1,-1}},
    {"Station_Side_D_End",	32,{-1,-1,-1}},
    {"CTCS_PADDING",	16,{-1,-1,-1}},
    };
    //std::vector<std::vector<unsigned char>> data_vector;
    void AnalyzeReceivedMsg(QVector<unsigned char> &input);

    struct AtpItem
    {
        QString name;
        qint64 value;
        QString remark;
    }ATPItem_Public[38]=
    {
        {"m_MAIN_POS_TRAIN",-1,"列车当前位置,cm"},
        {"MAINT_VIT_TRAIN",-1,"列车当前速度,cm/s"},
        {"MAINT_VIT_PERMISE",-1,"列车当前允许速度,cm"},
        {"CTCS_TRAIN_LENGTH",-1,"车长,0-未知，1-单组，2-双组"},
        {"MAINT_L_DOUBTUNDER",-1,"最大车头误差,cm"},
        {"MAINT_L_DOUBTOVER",-1,"最小车头误差,cm"},
        {"CTCS_LEVEL",-1,"当前列控等级,0-Level_0,1-Level_1,2-Level_2,3-Level_3 ,4-Level_4"},//6
        {"CTCS_MODE",-1,"当前控车模式"},
        {"CTCS_D_EOA",-1,"当前MA长度,MA位置，cm"},
        {"MAINT_CMD_FU",-1,"列车当前制动状态-紧急,EB"},
        {"MAINT_CMD_FS",-1,"列车当前制动状态-常用,SB7"},
        {"CTCS_YEAR_TO_LKJ",-1,"年"},//11
        {"CTCS_MONTH_TO_LKJ",-1,"月"},//12
        {"CTCS_DAY_TO_LKJ",-1,"日"},//13
        {"CTCS_HOUR_TO_LKJ",-1,"时"},//14
        {"CTCS_MINUTES_TO_LKJ",-1,"分"},//15
        {"CTCS_SECONDS_TO_LKJ",-1,"秒"},//16
        {"CTCS_Text_Code",-1,"DMI文本显示"},//17
        {"MAINT_VIT_PRE_INTERV",-1,"对应DMI规范的Vint,干预速度,cm/s"},
        {"MAINT_VIT_OBJECTIF",-1,"对应DMI规范的Vtarget,目标速度cm/s"},
        {"CTCS_CODE",-1,"当前轨道电路载频,0-NO_CODE,1-L3,2-L,3-L2,4-LU,5-U2,6-LU2,7-U, 8-UU, 9-UUS, 10-U2S, 11-L5, 12-U3, 13-L4, 14-HB, 15-25.7,16-HU,17-27.9,18-H"},
        {"CTCS_CARRIER",-1,"当前轨道电路低频,0-F_0000, 1-F_1700, 2-F_2000, 3-F_2300, 4-F_2600,5-F1_1700,6-F2_1700,7-F1_2000,8-F2_2000,9-F1_2300,10-F2_2300, 11-F1_2600,12-F2_2600,13-F_550,14-F_650, 15-F_750,16-F_850,17-F_550_750,18-F_650_850,19-F_1698p7_1701p4,20-F_1998p7_2001p4, 21-F_2298p7_2301p4, 22-F_2598p7_2601p4, 23-F_1700_2300, 24-F_2000_2600, 25-F_1698p7_2298p7, 26-F_1698p7_2301p4, 27-F_1701p4_2298p7, 28-F_1701p4_2301p4, 29-F_1998p7_2598p7, 30-F_1998p7_2601p4, 31-F_2001p4_2598p7, 32-F_2001p4_2601p4,33-F_Unknown"},
		{ "CURRENT_LETTER_CODE_1",-1,""},//车次号
		{ "CURRENT_LETTER_CODE_2",-1,"" },//车次号
		{ "CURRENT_LETTER_CODE_3",-1,"" },//车次号
		{ "CURRENT_DIGIT_CODE_1",-1,"" },//车次号
		{ "CURRENT_DIGIT_CODE_1",-1,"" },//车次号
		{ "CURRENT_DIGIT_CODE_1",-1,"" },//车次号
		{ "CURRENT_DIGIT_CODE_1",-1,"" },//车次号
		{ "CURRENT_DIGIT_CODE_1",-1,"" },//车次号
        { "MAINT_POS_GEO",-1,"" },//当前公里标位置，30
        //2018-7-24新添加的200c解析数据
        {"CTCS_TTS_TO_LKJ",-1,"毫秒"},//31
        {"MAINT_DIS_OBJECTIF",-1,"目标距离"},//32
        {"MAINT_KV_VIT_CTRL_FU",-1,"EBP速度"},//33
        {"CTCS_FS_FAIBLE",-1,"SB1"},//34
        {"CTCS_FS_MOYEN",-1,"SB4"},//35
        {"CTCS_DRIVER_ID_1",-1,"司机编号的第一部分"},//36
        {"CTCS_DRIVER_ID_2",-1,"司机编号的第二部分"},//37
},
    ATPItem_CTCS_1[22]=
    {
        {"CTCS_ENTER_NEW_SECTION",-1,"是否进入新的区段"},
        {"CTCS_COUNT_SECTIONS",-1,"轨道区段个数"},
        //以下为5个区段的信息
        {"CTCS_SECTION_NID_SIGNAL_1",-1,"末端信号机类型"},
        {"CTCS_SECTION_NID_FREQUENCY_1",-1,"载频/定义同CTCS_CARRIER"},
        {"CTCS_SECTION_D_START_1",-1,"起点/cm"},
        {"CTCS_SECTION_D_END_1",-1,"终点/cm"},

        {"CTCS_SECTION_NID_SIGNAL_2",-1,"末端信号机类型"},
        {"CTCS_SECTION_NID_FREQUENCY_2",-1,"载频/定义同CTCS_CARRIER"},
        {"CTCS_SECTION_D_START_2",-1,"起点/cm"},
        {"CTCS_SECTION_D_END_2",-1,"终点/cm"},

        {"CTCS_SECTION_NID_SIGNAL_3",-1,"末端信号机类型"},
        {"CTCS_SECTION_NID_FREQUENCY_3",-1,"载频/定义同CTCS_CARRIER"},
        {"CTCS_SECTION_D_START_3",-1,"起点/cm"},
        {"CTCS_SECTION_D_END_3",-1,"终点/cm"},

        {"CTCS_SECTION_NID_SIGNAL_4",-1,"末端信号机类型"},
        {"CTCS_SECTION_NID_FREQUENCY_4",-1,"载频/定义同CTCS_CARRIER"},
        {"CTCS_SECTION_D_START_4",-1,"起点/cm"},
        {"CTCS_SECTION_D_END_4",-1,"终点/cm"},

        {"CTCS_SECTION_NID_SIGNAL_5",-1,"末端信号机类型"},
        {"CTCS_SECTION_NID_FREQUENCY_5",-1,"载频/定义同CTCS_CARRIER"},
        {"CTCS_SECTION_D_START_5",-1,"起点/cm"},
        {"CTCS_SECTION_D_END_5",-1,"终点/cm"},
    },
    ATPItem_ETCS_79[1]=
    {
        {"MAINT_POS_ODO",-1,"列车当前公里标"}
    },
    ATPItem_ETCS_27[24]=
    {
        {"MAINT_NB_SSP",-1,"变速点个数"},
        {"MAINT_FIN_SSP",-1,"SSP总数据的终点/cm"},
        //以下描述前11个变速点的信息
        {"MAINT_SSP_DIST_1",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_1",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_2",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_2",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_3",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_3",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_4",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_4",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_5",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_5",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_6",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_6",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_7",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_7",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_8",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_8",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_9",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_9",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_10",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_10",-1,"速度值/cm/s"},

        {"MAINT_SSP_DIST_11",-1,"变速点距离/cm"},
        {"MAINT_SSP_VIT_11",-1,"速度值/cm/s"},
    },
    ATPItem_ETCS_21[17]=
    {
        {"MAINT_NB_PENTE",-1,"变坡点个数"},
        {"MAINT_PENTE_FIN",-1,"坡度总数据的终点/cm"},
        //以下描述前5个变坡点的信息
        {"MAINT_PENTE_POS_1",-1,"第一个变坡点的位置/cm"},
        {"MAINT_PENTE_GDIR_1",-1,"1-上坡，0-下坡或平坡"},
        {"MAINT_PENTE_1",-1,"坡度值"},

        {"MAINT_PENTE_POS_2",-1,"第一个变坡点的位置/cm"},
        {"MAINT_PENTE_GDIR_2",-1,"1-上坡，0-下坡或平坡"},
        {"MAINT_PENTE_2",-1,"坡度值"},

        {"MAINT_PENTE_POS_3",-1,"第一个变坡点的位置/cm"},
        {"MAINT_PENTE_GDIR_3",-1,"1-上坡，0-下坡或平坡"},
        {"MAINT_PENTE_3",-1,"坡度值"},

        {"MAINT_PENTE_POS_4",-1,"第一个变坡点的位置/cm"},
        {"MAINT_PENTE_GDIR_4",-1,"1-上坡，0-下坡或平坡"},
        {"MAINT_PENTE_4",-1,"坡度值"},

        {"MAINT_PENTE_POS_5",-1,"第一个变坡点的位置/cm"},
        {"MAINT_PENTE_GDIR_5",-1,"1-上坡，0-下坡或平坡"},
        {"MAINT_PENTE_5",-1,"坡度值"},
    },
    ATPItem_ETCS_5[6]=
    {
        {"CTCS_ID_REGION",-1,"NID_C地区编号"},
        {"MAINT_DERNIERE_RECUE_ID_BAL",-1,"NID_BG应答器组编号"},
        {"CTCS_ID_ETCS",-1,"NID_BG应答器组编号"},
        {"MAINT_LOC_ID_BALISE_ATTENDUE",-1,"下一组应答器组编号"},
        {"MAINT_LOC_POS_BALISE_ATTENDUE",-1,"下一个应答器组的位置"},
        {"MAINT_LOC_SENS_BALISE_ATTENDUE",-1,"列车通过被链接应答器组时的运行方向"},
    },
    ATPItem_CTCS_2[1]=
    {
        {"CTCS_L_TSR",-1,"临时限速范围的剩余长度，cm"},
    },
    ATPItem_ETCS_72[31]=
    {
        {"MAINT_TEXT_LENGTH",-1,"应显示的文本区域长度"},
        {"MAINT_TEXT_BUFFER_01",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_02",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_03",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_04",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_05",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_06",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_07",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_08",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_09",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_10",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_11",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_12",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_13",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_14",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_15",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_16",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_17",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_18",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_19",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_20",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_21",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_22",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_23",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_24",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_25",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_26",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_27",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_28",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_29",-1,"文本字节值"},
        {"MAINT_TEXT_BUFFER_30",-1,"文本字节值"},
    };
    qint64 m_MAIN_POS_TRAIN=0;

    void AnalyzeGetMainInfo(QVector<unsigned char>& input);
    int GetBelishMessage(const QVector<unsigned char> &input, BaliseBitMessage &BBM);
private:
    int offset_now=1600;
    const QVector<unsigned char>* ReceivedData;

    qint64 FetchValue(unsigned int length);

};
